<html>

<head>
<meta http-equiv="Content-Type"
content="text/html; charset=gb_2312-80">
<meta name="GENERATOR" content="Microsoft FrontPage Express 2.0">
<title>老兵新传-网络杂闻-录音带疑曾复制　特里普也涉伪证)</title>
<bgsound src="../../wav/003.mid" loop="infinite">
</head>

<body bgcolor="#FFFFFF" vlink="#FF0000" alink="#AAAAAA">
<div align="center"><center>

<table border="1" width="75%">
    <tr>
        <td bgcolor="#00FF00"><a href="../../right.htm"
        onmouseover="window.status='技术监督 网络杂闻 明星荟萃...'; return true"><font
        size="2">主页</font></a><font size="2"><strong>》</strong></font><a
        href="../zawen.html#网 络 杂 闻"
        onmouseover="window.status='网络上的趣闻轶事...'; return true"><font
        size="2">网络杂闻</font></a><font size="2"><strong>》</strong></font></td>
    </tr>
</table>
</center></div>

<h2 align="center"><font color="#0000FF">录音带疑曾复制　特里普也涉伪证　斯塔尔展开调查</font></h2>

<hr>

<p>独立检察官斯塔尔正在调查特里普是否在她秘密录下与莱温斯基的谈话一事上撒谎。<br>
　　联邦调查局在维珍尼亚州的语音讯号分析小组发现，特里普所提供的录音带中，有九卷和她当初作证时供称所使用的机器不符。<br>
　　周一由众议院所公布的斯塔尔报告文件中显示，特里普的九卷录音带中，七卷含有复制过的痕迹，而且是使用单卷录音带的录音机所录制而成。
<br>
　　斯塔尔办公室的声明中指出：“特里普女士若曾经复制这些录音带或者知道这些复制带的存在，那麽，她在大陪审团面前作证时即在说谎。”报告书中显示，独立检察官办公室正在为此事进行调查。<br>
　　特里普的发言人寇特说，检察官报告中指称特里普说谎一事“不属实”。寇特拒绝再对此事多表示意见。
<br>
　　特里普是莱温斯基在国防部的同事，莱向特里普透露与克林顿的关系，特里普秘密录下二人之间的谈话，成为引发本案调查的起点。
</p>
<div align="left">

<table border="0" width="600" bgcolor="#00FF00">
    <tr>
        <td width="50%"><a href="../../right.htm"
        onmouseover="window.status='技术监督 网络杂闻 明星荟萃...'; return true"><font
        size="2">主页</font></a><font size="2"><strong>》</strong></font><a
        href="../zawen01.html#网 络 杂 闻"
        onmouseover="window.status='网络上的趣闻轶事...'; return true"><font
        size="2">网络杂闻目录</font></a><font size="2"><strong>》</strong></font></td>
        <td align="right" width="50%"><a href="1-5.htm">上一条</a>&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="1-7.htm">下一条</a></td>
    </tr>
</table>
</div>
</body>
</html>
