document.write('')
document.write("<CENTER><font size=5 color=#ff0000>送给我心荡漾！</font><br>请点击那个蜻蜓<br><br>")
document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="../../active.macromedia.com/flash2/cabs/swflash.cab#version=2,0,0,0" ID=1102 WIDTH=250 HEIGHT=188><PARAM NAME=movie VALUE="http://person.zj.cninfo.net/~laotong/gp/flash10.swf"><PARAM NAME=quality VALUE=high><PARAM NAME=bgcolor VALUE=#000000>')
document.write('<EMBED SRC="flash10.swf" swLiveConnect=FALSE WIDTH=250 HEIGHT=188 QUALITY=high BGCOLOR=#ffffff TYPE="application/x-shockwave-flash"></EMBED><PARAM NAME=wmode VALUE=transparent></OBJECT></CENTER> ')

