document.write('')
document.write("<div id='Layer1' style='position:absolute; width:500px; height:123px; z-index:2'><a href=#【天下有雪】（论坛） onClick=window.open('http://dax2001.ok100.net/')><FONT COLOR=#FF0000 SIZE=4>HTTP：//DAX3001.OK100.NET</FONT></a><br>")
document.write('<font color=#660000 size=2>做男人难，做股票的男人更难，做一个成功的做股票的男人更是难上加难!<br> ')
document.write('做一个成功的每年翻30倍的做股票的男人更是难上加难再加难。</font><br></div><br>')
document.write('<div id="Layer2" style="position:absolute; width:500px; height:62px; z-index:1;"><span style="font-size:24px;line-height:24pt;font-family: 繁琥珀;color: #c0c081">难!难!难!难!难!难!难!难!难!</span></div><br><br>')

