document.write('')
document.write("<a href=#【天下有雪】（论坛） onClick=window.open('http://dax2001.ok100.net/')><IMG SRC='http://person.zj.cninfo.net/~laotong/gp/yjlc.gif' BORDER=0 ALT='【天下有雪】（论坛）'></a><br><br>")
var marqueewidth=250
var marqueeheight=50
var speed=2
var marqueecontents='<span style="font-size:12px;line-height:14pt;font-family: 宋体;color: #AA0000">'+'你的灵魂在我的身边萦绕<br>美丽的幻梦我曾用心制造<br>荒谬的世界唯一的真理<br>竟是你那单纯的笑<br>我绝望的泪水不再等待奇迹<br>也不想用暗淡的青春陪伴孤零零的星<br>当封闭的角落挡住窥探的眼<br>仿佛天使般的贞操扑向邪恶的火<br><br>'+'</span>'
if (document.all)
document.write('<marquee direction="up" scrollAmount='+speed+' style="width:'+marqueewidth+';height:'+marqueeheight+'">'+marqueecontents+'</marquee>')
