document.write('')
document.write("<a href=#【老童之家】（个人网站） onClick=window.open('http://laotong.126.com')><IMG SRC='http://person.zj.cninfo.net/~laotong/laotong.gif' BORDER=0 ALT='【欢迎访问老兵新传--老童之家】'></a><br><br>")
document.write("<li><a href=#【上海证券交易所】（公告） onClick=window.open('http://www.sse.com.cn/list2.htm')>【上海证券交易所】（公告）</a><font color=#ff0000> (最新)</font><br><br>")
document.write("<li><a href=#【上海证券交易所】（每日行情） onClick=window.open('http://www.sse.com.cn/show.htm')>【上海证券交易所】（每日行情）</a><font color=#ff0000> (最新)</font><br><br>")
