#################### 请修改下面内容 #####################
########################################################
#            本程序为Yuzi工作室 梦之星 提供              #
#        Yuzi 更新小记+站长小记 2001多用户版v1.2         #
#                                                      #
#     本程序版权归Yuzi工作室 梦之星 所有！任何人          #
#     皆可自由使用本程序于非商业用途，商业用途必          #
#     须付费人民币500元！                               #
#                                                      #
#                    谢谢您使用本程序　　梦之星          #
#                    E-mail: webmaster@popcgi.com      #
#                    http://www.yuzi.net	              #
#                                                      #
#     本程序为免费程序，您可以使用本程序，但必须          #
#     保留Yuzi工作室(http://www.yuzi.net)的链接！       #
########################################################
##################################
$adminname="win918";   # 管理用户名
$adminpass="win91812345";  # 管理密码
$adminmail="laotong\@ah163.com";  # 管理员邮箱，@前必须加“\”。
$cgi_url="http://cgi.laotong.533.net/new2001/new2001.cgi"; # 本程序链接
$filepath=".";  # 绝对路径
$image_url="http://laotong.533.net/new2001/images"; #图片链接
$net_name="赢家理财"; #网站名称
$net_url="http://www.win918.com"; #网站链接
$time_hour="0";  # Server时区调整
$time_out="60"; # 超时设定（单位分钟）
##################################
$bgcolor="#F4F9FF";#背景颜色
$datecolor="#1504B9";#日期颜色
$timecolor="#800080";#时间颜色
$fontcolor="#0909a9";#文字颜色
$fontcolor1="#cc0033";#文字颜色1
$linkcolor="#8000FF";#链接颜色
$Vlinkcolor="#008000";#访问过链接颜色
$Hlinkcolor="#FF0000";#链接颜色2
$TBcolor="#acbded";#表格背景
$DBcolor="#FCFEFF";#活跃对比颜色
$NOmessagecolor="#FF80C0";#没有信息时的颜色
##################################
$data_dir="$filepath/data";
$session_dir="$filepath/session";
###################################

1;